// src/app/components/Navigation.vue
<script setup lang="ts">
import { ref } from "vue";
import { BookOpen, PenTool, BarChart3, Settings, Menu, X } from "lucide-vue-next";
import Button from "./ui/Button.vue";
import Avatar from "./ui/Avatar.vue";
import AvatarFallback from "./ui/AvatarFallback.vue";

const props = defineProps<{
  activeTab: string;
}>();

const emit = defineEmits<{
  (e: "tabChange", tab: string): void;
}>();

const mobileMenuOpen = ref(false);

const tabs = [
  { id: "vocab", label: "Magic Vocab", icon: BookOpen },
  { id: "grammar", label: "Grammar Check", icon: PenTool },
  { id: "stats", label: "Stats & Streaks", icon: BarChart3 },
];

const handleTabClick = (tabId: string) => {
  emit("tabChange", tabId);
  mobileMenuOpen.value = false;
};
</script>

<template>
  <nav class="fixed top-0 left-0 right-0 z-50 bg-white shadow-sm">
    <div class="max-w-7xl mx-auto px-4 md:px-8">
      <div class="flex items-center justify-between h-16">
        <!-- Logo -->
        <div class="flex items-center gap-2">
          <div class="w-8 h-8 bg-gradient-to-br from-emerald-500 to-teal-500 rounded-lg flex items-center justify-center">
            <BookOpen class="w-5 h-5 text-white" />
          </div>
          <span class="font-bold text-xl text-gray-900">Magic English</span>
        </div>

        <!-- Desktop Navigation Tabs -->
        <div class="hidden md:flex items-center gap-2">
          <Button
            v-for="tab in tabs"
            :key="tab.id"
            :variant="activeTab === tab.id ? 'default' : 'ghost'"
            @click="emit('tabChange', tab.id)"
            :class="
              activeTab === tab.id
                ? 'bg-emerald-500 hover:bg-emerald-600'
                : ''
            "
          >
            <component :is="tab.icon" class="w-4 h-4 mr-2" />
            {{ tab.label }}
          </Button>
        </div>

        <!-- User Section -->
        <div class="flex items-center gap-2">
          <Button variant="ghost" size="icon" class="hidden md:flex">
            <Settings class="w-5 h-5" />
          </Button>
          <Avatar class="hidden md:flex">
            <AvatarFallback class="bg-emerald-100 text-emerald-700">
              ME
            </AvatarFallback>
          </Avatar>
          
          <!-- Mobile Menu Button -->
          <Button
            variant="ghost"
            size="icon"
            class="md:hidden"
            @click="mobileMenuOpen = !mobileMenuOpen"
          >
            <X v-if="mobileMenuOpen" class="w-6 h-6" />
            <Menu v-else class="w-6 h-6" />
          </Button>
        </div>
      </div>

      <!-- Mobile Menu -->
      <div v-if="mobileMenuOpen" class="md:hidden pb-4 space-y-2">
        <Button
          v-for="tab in tabs"
          :key="tab.id"
          :variant="activeTab === tab.id ? 'default' : 'ghost'"
          @click="handleTabClick(tab.id)"
          :class="`w-full justify-start ${
            activeTab === tab.id
              ? 'bg-emerald-500 hover:bg-emerald-600'
              : ''
          }`"
        >
          <component :is="tab.icon" class="w-4 h-4 mr-2" />
          {{ tab.label }}
        </Button>
      </div>
    </div>
  </nav>
</template>

// src/app/components/Navigation.tsx
import { BookOpen, PenTool, ChartBar, Settings, Menu, X } from "lucide-react";
import { Button } from "./ui/button";
import { Avatar, AvatarFallback } from "./ui/avatar";
import { useState } from "react";

interface NavigationProps {
  activeTab: string;
  onTabChange: (tab: string) => void;
}

export function Navigation({ activeTab, onTabChange }: NavigationProps) {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  
  const tabs = [
    { id: "vocab", label: "Magic Vocab", icon: BookOpen },
    { id: "grammar", label: "Grammar Check", icon: PenTool },
    { id: "stats", label: "Stats & Streaks", icon: ChartBar },
  ];

  const handleTabClick = (tabId: string) => {
    onTabChange(tabId);
    setMobileMenuOpen(false);
  };

  return (
    <nav className="fixed top-0 left-0 right-0 z-50 bg-white shadow-sm">
      <div className="max-w-7xl mx-auto px-4 md:px-8">
        <div className="flex items-center justify-between h-16">
          {/* Logo */}
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-gradient-to-br from-emerald-500 to-teal-500 rounded-lg flex items-center justify-center">
              <BookOpen className="w-5 h-5 text-white" />
            </div>
            <span className="font-bold text-xl text-gray-900">Magic English</span>
          </div>

          {/* Desktop Navigation Tabs */}
          <div className="hidden md:flex items-center gap-2">
            {tabs.map((tab) => {
              const Icon = tab.icon;
              return (
                <Button
                  key={tab.id}
                  variant={activeTab === tab.id ? "default" : "ghost"}
                  onClick={() => onTabChange(tab.id)}
                  className={
                    activeTab === tab.id
                      ? "bg-emerald-500 hover:bg-emerald-600"
                      : ""
                  }
                >
                  <Icon className="w-4 h-4 mr-2" />
                  {tab.label}
                </Button>
              );
            })}
          </div>

          {/* User Section */}
          <div className="flex items-center gap-2">
            <Button variant="ghost" size="icon" className="hidden md:flex">
              <Settings className="w-5 h-5" />
            </Button>
            <Avatar className="hidden md:flex">
              <AvatarFallback className="bg-emerald-100 text-emerald-700">
                ME
              </AvatarFallback>
            </Avatar>
            
            {/* Mobile Menu Button */}
            <Button
              variant="ghost"
              size="icon"
              className="md:hidden"
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            >
              {mobileMenuOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
            </Button>
          </div>
        </div>

        {/* Mobile Menu */}
        {mobileMenuOpen && (
          <div className="md:hidden pb-4 space-y-2">
            {tabs.map((tab) => {
              const Icon = tab.icon;
              return (
                <Button
                  key={tab.id}
                  variant={activeTab === tab.id ? "default" : "ghost"}
                  onClick={() => handleTabClick(tab.id)}
                  className={`w-full justify-start ${
                    activeTab === tab.id
                      ? "bg-emerald-500 hover:bg-emerald-600"
                      : ""
                  }`}
                >
                  <Icon className="w-4 h-4 mr-2" />
                  {tab.label}
                </Button>
              );
            })}
          </div>
        )}
      </div>
    </nav>
  );
}
