// src/app/App.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { Toaster, toast } from 'vue-sonner'
import Navigation from "./components/Navigation.vue";
import WelcomeScreen from "./components/WelcomeScreen.vue";
import MagicVocab from "./components/MagicVocab.vue";
import GrammarChecker from "./components/GrammarChecker.vue";
import StatsStreaks from "./components/StatsStreaks.vue";
import { initializeSampleData, loadSampleData, skipSampleData } from "./utils/sampleData";

// Dialog components
import Dialog from "./components/ui/Dialog.vue";
import DialogContent from "./components/ui/DialogContent.vue";
import DialogHeader from "./components/ui/DialogHeader.vue";
import DialogTitle from "./components/ui/DialogTitle.vue";
import DialogDescription from "./components/ui/DialogDescription.vue";
import DialogFooter from "./components/ui/DialogFooter.vue";
import Button from "./components/ui/Button.vue";

const activeTab = ref("vocab")
const showWelcome = ref(false)
const showSampleDataDialog = ref(false)

onMounted(() => {
  const hasVisited = localStorage.getItem("magicEnglishVisited")
  if (!hasVisited) {
    showWelcome.value = true
  }

  // Check if we should offering sample data
  if (initializeSampleData()) {
    showSampleDataDialog.value = true;
  }
})

const handleGetStarted = () => {
  localStorage.setItem("magicEnglishVisited", "true")
  showWelcome.value = false
}

const handleLoadSampleData = () => {
  loadSampleData();
  toast.success("Đã tải dữ liệu mẫu thành công!");
  showSampleDataDialog.value = false;
  // Trigger a reload or event to update MagicVocab if needed. 
  // Since MagicVocab reads on mount, it might need a re-mount or watcher.
  // We can force re-render by key or just reload page.
  window.location.reload();
}

const handleSkipSampleData = () => {
  skipSampleData();
  showSampleDataDialog.value = false;
}
</script>

<template>
  <div class="min-h-screen bg-gray-50">
    <Navigation
      :activeTab="activeTab"
      @tabChange="(tab) => activeTab = tab"
    />
    
    <WelcomeScreen
      v-if="showWelcome"
      @getStarted="handleGetStarted"
    />

    <template v-else>
      <MagicVocab v-if="activeTab === 'vocab'" />
      
      <GrammarChecker v-if="activeTab === 'grammar'" />
      <StatsStreaks v-if="activeTab === 'stats'" />
      
      <div v-if="activeTab !== 'vocab' && activeTab !== 'grammar' && activeTab !== 'stats'" class="pt-20 p-4">
        <h1 class="text-3xl font-bold text-emerald-600 text-center">Work in Progress</h1>
        <p class="text-center mt-4">Active Tab: {{ activeTab }}</p>
      </div>
    </template>
    
    <!-- Sample Data Dialog -->
    <Dialog v-model:open="showSampleDataDialog">
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Tải dữ liệu mẫu?</DialogTitle>
          <DialogDescription>
            Bạn có muốn tải một số từ vựng mẫu để trải nghiệm ứng dụng ngay lập tức không?
          </DialogDescription>
        </DialogHeader>
        <DialogFooter>
          <Button variant="ghost" @click="handleSkipSampleData">Không, cảm ơn</Button>
          <Button @click="handleLoadSampleData" class="bg-emerald-500 hover:bg-emerald-600">Tải Dữ Liệu Mẫu</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>

    <Toaster position="top-right" />
  </div>
</template>

// src/app/App.tsx
import { useState, useEffect } from "react";
import { Navigation } from "./components/Navigation";
import { MagicVocab } from "./components/MagicVocab";
import { GrammarChecker } from "./components/GrammarChecker";
import { StatsStreaks } from "./components/StatsStreaks";
import { WelcomeScreen } from "./components/WelcomeScreen";
import { Toaster } from "./components/ui/sonner";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "./components/ui/alert-dialog";
import {
  initializeSampleData,
  loadSampleData,
  skipSampleData,
} from "./utils/sampleData";

export default function App() {
  const [activeTab, setActiveTab] = useState("vocab");
  const [showWelcome, setShowWelcome] = useState(false);
  const [showSampleDataDialog, setShowSampleDataDialog] =
    useState(false);

  useEffect(() => {
    // Check if user has visited before
    const hasVisited = localStorage.getItem(
      "magicEnglishVisited",
    );
    if (!hasVisited) {
      setShowWelcome(true);
    } else {
      // Check if we should show sample data dialog
      const shouldShowSample = initializeSampleData();
      setShowSampleDataDialog(shouldShowSample);
    }
  }, []);

  const handleGetStarted = () => {
    localStorage.setItem("magicEnglishVisited", "true");
    setShowWelcome(false);

    // After welcome, check for sample data
    const shouldShowSample = initializeSampleData();
    setShowSampleDataDialog(shouldShowSample);
  };

  const handleLoadSampleData = () => {
    loadSampleData();
    setShowSampleDataDialog(false);
    // Refresh the page to show sample data
    window.location.reload();
  };

  const handleSkipSampleData = () => {
    skipSampleData();
    setShowSampleDataDialog(false);
  };

  if (showWelcome) {
    return (
      <>
        <Navigation
          activeTab={activeTab}
          onTabChange={setActiveTab}
        />
        <WelcomeScreen onGetStarted={handleGetStarted} />
        <Toaster position="top-right" />
      </>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <Navigation
        activeTab={activeTab}
        onTabChange={setActiveTab}
      />

      {activeTab === "vocab" && <MagicVocab />}
      {activeTab === "grammar" && <GrammarChecker />}
      {activeTab === "stats" && <StatsStreaks />}

      <Toaster position="top-right" />

      {/* Sample Data Dialog */}
      <AlertDialog
        open={showSampleDataDialog}
        onOpenChange={setShowSampleDataDialog}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>
              Bạn có muốn tải dữ liệu mẫu không?
            </AlertDialogTitle>
            <AlertDialogDescription>
              Để trải nghiệm ứng dụng tốt hơn, chúng tôi có thể
              tải sẵn 6 từ vựng mẫu và một chuỗi streak 5 ngày
              để bạn xem cách hoạt động của ứng dụng.
              <br />
              <br />
              Bạn có thể xóa dữ liệu này bất cứ lúc nào và thêm
              từ vựng của riêng mình.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel onClick={handleSkipSampleData}>
              Không, cảm ơn
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={handleLoadSampleData}
              className="bg-emerald-500 hover:bg-emerald-600"
            >
              Có, tải dữ liệu mẫu
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
